---
- name: apt-get update
  apt:
    update_cache=yes
    autoclean=yes
    autoremove=yes
    cache_valid_time=86400

- name: apt-get upgrade
  apt:
    upgrade=full

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot for maintenance"
  async: 1
  poll: 0
  ignore_errors: True
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 15
    timeout: 90
  become: False
  tags:
    - boot
    - shutdown
