- hosts: all
  name: Configure common stuff
  roles:
    - common

- hosts: master:node
  name: Prepare master and nodes
  roles:
    - docker
    - kubeadm

- hosts: master
  name: Bootstrap cluster
  roles:
    - master

- hosts: node
  name: Join nodes
  roles:
    - node
