---
- name: Install k8s Y'all
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - kubelet
    - kubeadm

- name: Configure kubelet to allow Swap
  copy:
    src: files/90-local-extras.conf
    dest: /etc/systemd/system/kubelet.service.d/90-local-extras.conf
  register: kubeletsrv_configuration

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
  when: kubeletsrv_configuration|changed

