---
- name: Install k8s Y'all
  apt:
    name: "{{ item }}"
    state: installed
    force: yes
  with_items:
    - kubelet={{ kubernetes_version }}
    - kubeadm={{ kubernetes_version }}

- name: Install ceph-common for rook.io
  apt:
    name: ceph-common
    state: latest
  tags:
    - pkgmgr

- name: Customize kubelet configuration
  copy:
    src: files/90-local-extras.conf
    dest: /etc/systemd/system/kubelet.service.d/90-local-extras.conf
  register: kubeletsrv_configuration

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
  when: kubeletsrv_configuration|changed

