apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-standard
parameters:
  openebs.io/capacity: 5G
  openebs.io/jiva-replica-count: "3"
  openebs.io/storage-pool: default
  openebs.io/volume-monitor: "true"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
