---
- name: Determine if Helm is installed
  stat:
    path: /usr/local/bin/helm
  register: helm_there
  ignore_errors: True

- name: Install kube-ops-view with Helm
  command: >
    helm install --namespace kube-ops-view --name dashboard
    --set image.repository=tobru/kube-ops-view-arm
    --set image.tag=latest
    --set image.pullPolicy=Always
    --set ingress.enabled=true
    --set rbac.create=true
    stable/kube-ops-view
  when: helm_there.stat.exists == True
