---
# tasks file for minions
- name: Reset Kubernetes
  shell: kubeadm reset
  register: kubeadm_reset
  when:
    - reset_kubeadm | default('no') | bool

- name: Join Kubernetes Cluster
  shell: kubeadm join --ignore-preflight-errors=all --token {{ token }} {{ groups['master'][0] }}:6443 --discovery-token-unsafe-skip-ca-verification
  register: kubeadm_join
  when:
    - kubeadm_reset | succeeded
    - reset_kubeadm | default('no') | bool

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
  when: kubeadm_join | succeeded
