---
# tasks file for common
- name: Enabling cgroup options at boot - Armbian
  lineinfile:
    dest: /boot/armbianEnv.txt
    line: 'extraargs=cgroup_enable=cpuset cgroup_enable=memory'
  register: cmdline
  tags:
    - boot

- name: Use Armbian beta package channel
  replace:
    dest: /etc/apt/sources.list.d/armbian.list
    regexp: '(.*)apt(.*)'
    replace: '\1beta\2'

- name: apt-get update
  apt:
    update_cache=yes
    autoclean=yes
    autoremove=yes
    cache_valid_time=86400

- name: apt-get upgrade
  apt:
    upgrade=full

- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible Reboot for Kernel cmdline Change"
  async: 1
  poll: 0
  ignore_errors: True
  when: cmdline|changed
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 15
    timeout: 90
  become: False
  when: cmdline|changed
  tags:
    - boot
    - shutdown
