---
# Docker Convenience Script Can Only Be Run Once
- name: Determine if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_there
  ignore_errors: True

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-using-the-convenience-script
- name: Run Docker Install Script
  script: files/get-docker.sh
  when: docker_there.stat.exists == False

- name: Add Ansible User to Docker Group
  user:
    name: ansible
    groups: docker
    append: yes

